# Use container-based arch
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: scala
scala:
   - 2.11.5

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2

sbt_args:
  - 'set javaOptions += "-Djunit.parallel.threads=1"'
  - 'set parallelExecution in Test := false'
