# Use container-based arch
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: scala
scala:
   - 2.11.6

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2

script:
  - sbt ++$TRAVIS_SCALA_VERSION 'set javaOptions += "-Djunit.parallel.threads=1"' 'set parallelExecution in Test := false' test

